project_id = "iqmoaqphafuvotwmtycb"

[api]
enabled = true
port = 54321

[functions.generate-cards]
verify_jwt = false

[functions.review-card]
verify_jwt = false

[functions.link-telegram]
verify_jwt = false
